/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Iterator;
import java.util.function.Consumer;
import java.util.function.Supplier;

import jakarta.servlet.ServletException;
import jakarta.xml.soap.*;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.servlet.ServletHandler;

import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import lombok.SneakyThrows;

@WebServlet("/score")
public class App extends HttpServlet {
    private MessageFactory factory;

    @Override
    @SneakyThrows
    public void init() {
        factory = MessageFactory.newInstance(SOAPConstants.SOAP_1_2_PROTOCOL);
    }

    @Override
    @SneakyThrows
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) {
        var msg = factory.createMessage();
        var body = msg.getSOAPBody();
        var se = msg.getSOAPPart().getEnvelope();
        var reply = ((Supplier<Void>) () -> {
            try {
                msg.saveChanges();
                msg.writeTo(resp.getOutputStream());
            } catch (Exception e) {
                // ignore
            }
            return null;
        });

        se.addNamespaceDeclaration("", "http://www.jw.nju.edu.cn/schema");
        resp.setStatus(HttpServletResponse.SC_OK);
        resp.setHeader("Content-Type", "text/xml");

        var id = 0;
        if (req.getParameter("id") == null) {
            body.addFault(se.createQName("Receiver", "env"), "No parameter id");
            reply.get();
            return;
        }

        try {
            id = Integer.parseInt(req.getParameter("id"));
        } catch (Exception e) {
            body.addFault(se.createQName("Receiver", "env"), "invalid input id");
            reply.get();
            return;
        }

        var grades = Grades.scores.get(id);
        if (grades == null) {
            body.addFault(se.createQName("Receiver", "env"), "Student id not found");
            reply.get();
            return;
        }

        var list = body.addChildElement(se.createName("课程成绩列表"));
        for (var grade : grades) {
            var elem = list.addChildElement("课程成绩");
            elem.addAttribute(se.createName("成绩性质"), grade.type);
            elem.addAttribute(se.createName("课程编号"), grade.courseId.toString());
            var g = elem.addChildElement("成绩");
            g.addChildElement("学号").setTextContent(grade.id.toString());
            g.addChildElement("得分").setTextContent(grade.grade.toString());
        }
        reply.get();
    }

    @Override
    @SneakyThrows
    protected void doPost(HttpServletRequest req, HttpServletResponse resp){
        var msg = factory.createMessage();
        var body = msg.getSOAPBody();
        var se = msg.getSOAPPart().getEnvelope();
        var reply = ((Supplier<Void>) () -> {
            try {
                msg.saveChanges();
                msg.writeTo(resp.getOutputStream());
            } catch (Exception e) {
                // ignore
            }
            return null;
        });

        se.addNamespaceDeclaration("", "http://www.jw.nju.edu.cn/schema");
        resp.setStatus(HttpServletResponse.SC_OK);
        resp.setHeader("Content-Type", "text/xml");

        InputStream inputStream = req.getInputStream();
        MimeHeaders headers = new MimeHeaders();
        try{
            var postMsg = factory.createMessage(headers,inputStream);
            var postBody = postMsg.getSOAPBody();
            var iterator = postBody.getChildElements();
            SOAPElement scoreListElement = (SOAPElement) iterator.next();
            if(scoreListElement!=null){
                var scoreElement = (SOAPElement) scoreListElement.getChildElements().next();
                String courseType = scoreElement.getAttribute("jw:成绩性质");
                String courseId = scoreElement.getAttribute("jw:课程编号");
                var scoreInfo = (SOAPElement) scoreElement.getChildElements().next();
                String studentId = scoreInfo.getFirstChild().getTextContent();
                String courseScore = scoreInfo.getLastChild().getTextContent();
                System.out.println("成绩性质："+courseType);
                System.out.println("课程编号"+courseId);
                System.out.println("学号："+studentId);
                System.out.println("成绩："+courseScore);
                if(courseType.equals("")||courseId.equals("")||studentId.equals("")||courseScore==null){
                    body.addFault(se.createQName("Receiver", "env"), "成绩性质，课程编号，学号，成绩均不可以为空");
                    reply.get();
                    return;
                }

                var grades = Grades.scores.get(Integer.parseInt(studentId));
                if (grades == null) {
                    body.addFault(se.createQName("Receiver", "env"), "学生不存在");
                    reply.get();
                    return;
                }
                //将拿到的数据修改
                //输出修改后的数据
                var list = body.addChildElement(se.createName("课程成绩列表"));
                var elem = list.addChildElement("课程成绩");
                elem.addAttribute(se.createName("成绩性质"),courseType);
                elem.addAttribute(se.createName("课程编号"), courseId);
                var g = elem.addChildElement("成绩");
                g.addChildElement("学号").setTextContent(studentId);
                g.addChildElement("得分").setTextContent(courseScore);
                reply.get();
            }
        }catch (IOException e){
            body.addFault(se.createQName("Receiver", "env"), "输入不合法");
            reply.get();
            return;
        }catch(SOAPException e){
            body.addFault(se.createQName("Receiver", "env"), "输入不合法");
            reply.get();
            return;
        }
    }

    @SneakyThrows
    public static void main(String[] args) {
        var server = new Server();
        var conn = new ServerConnector(server);
        conn.setPort(8080);
        server.setConnectors(new ServerConnector[] { conn });

        var handler = new ServletHandler();
        server.setHandler(handler);
        handler.addServletWithMapping(App.class, "/score/*");

        server.start();
    }
}
